import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography } from '../../../shared/styles';

const { height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  modalContainer: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  contentContainer: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flex: 1,
    maxHeight: screenHeight * 0.85,
  },  
  handle: {
    width: 40,
    height: 4,
    backgroundColor: colors.border.medium,
    borderRadius: 2,
    alignSelf: 'center',
    marginVertical: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
    backgroundColor: colors.surface,
  },
  avatarContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary + '20',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 56,
    height: 56,
  },
  headerInfo: {
    flex: 1,
  },
  nameAndStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 4,
  },
  nombre: {
    ...typography.styles.h3,
    fontSize: 20,
    color: colors.text.primary,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  ubicacionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  ubicacion: {
    ...typography.styles.caption,
    color: colors.text.secondary,
  },
  distanceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fceeeeff',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
    borderWidth: 1,
    borderColor: '#f5a3c1ff',
  },
  distanceText: {
    ...typography.styles.caption,
    fontSize: 12,
    color: '#f5a3c1ff',
    fontWeight: '600',
  },
  reservaPara: {
    ...typography.styles.body2,
    fontSize: 13,
    color: colors.text.secondary,
    marginTop: 6,
  },
  closeButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.surfaceVariant,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ScrollView debe ocupar el espacio entre header y botones
  scrollContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  scrollContent: {
    paddingTop: 4,
    paddingBottom: 100,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    ...typography.styles.bodyBold,
    fontSize: 16,
    color: colors.text.primary,
    marginBottom: 12,
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  contactText: {
    ...typography.styles.body,
    color: colors.text.secondary,
    marginLeft: 12,
    flex: 1,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  infoText: {
    ...typography.styles.body,
    color: colors.text.secondary,
    marginLeft: 12,
    flex: 1,
  },
  descripcion: {
    ...typography.styles.body,
    color: colors.text.secondary,
    lineHeight: 22,
  },
  mascotaList: {
    gap: 12,
  },
  mascotaBlock: {
    backgroundColor: colors.surfaceVariant,
    borderRadius: 12,
    padding: 14,
    marginBottom: 4,
  },
  mascotaBlockHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  mascotaBlockEmoji: {
    fontSize: 22,
    marginRight: 10,
  },
  mascotaBlockTitle: {
    ...typography.styles.bodyBold,
    fontSize: 16,
    color: colors.text.primary,
    flex: 1,
  },
  mascotaBlockContent: {
    paddingLeft: 2,
  },
  mascotaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  mascotaLabel: {
    ...typography.styles.bodyBold,
    fontSize: 14,
    color: colors.text.primary,
    minWidth: 140,
  },
  mascotaValue: {
    ...typography.styles.body,
    fontSize: 14,
    color: colors.text.secondary,
    flex: 1,
    lineHeight: 20,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  stepNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primaryDark,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 2,
    flexShrink: 0,
  },
  stepNumberText: {
    ...typography.styles.caption,
    fontWeight: '800',
    color: colors.text.inverse,
    fontSize: 12,
  },
  stepText: {
    ...typography.styles.body,
    color: colors.text.secondary,
    flex: 1,
    lineHeight: 20,
  },
  // Warning section
  warningContainer: {
    backgroundColor: colors.surfaceVariant,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    borderLeftWidth: 4,
    borderLeftColor: colors.primaryDark,
  },
  warningHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  warningIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  warningTitle: {
    ...typography.styles.bodyBold,
    fontSize: 15,
    color: colors.text.primary,
  },
  warningContent: {
    gap: 8,
  },
  warningText: {
    ...typography.styles.body,
    fontSize: 14,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  // Botones fijos
  actionsContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  actionBtn: {
    flex: 1,
    flexBasis: 0,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 0,
  },
  actionBtnChat: {
    minHeight: 58,
  },
  actionBtnPrimary: {
    backgroundColor: colors.primaryDark,
    shadowColor: colors.primaryDark,
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  actionBtnSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  actionBtnTextPrimary: {
    ...typography.styles.button,
    fontWeight: '600',
    letterSpacing: 0.5,
    color: colors.text.inverse,
  },
  actionBtnTextSecondary: {
    ...typography.styles.button,
    fontWeight: '600',
    letterSpacing: 0.5,
    color: colors.text.primary,
  },
  actionBtnTextCentered: {
    textAlign: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
});
