import { StyleSheet } from "react-native";
import { colors, typography } from "../../shared/styles";

const styles = StyleSheet.create({
  section: {
    paddingVertical: 40,
    paddingHorizontal: 20,
    backgroundColor: colors.backgroundLanding,
  },
  header: {
    alignItems: "center",
    marginBottom: 40,
  },
  title: {
    ...typography.styles.h2,
    color: colors.text.primary,
    marginBottom: 12,
    textAlign: "center",
  },
  subtitle: {
    ...typography.styles.body,
    color: colors.text.secondary,
    textAlign: "center",
    maxWidth: 500,
    lineHeight: 22,
    fontSize: 16,
  },
  plansWrapper: {
    maxWidth: 1000,
    width: "100%",
    alignSelf: "center",
  },
  duenioInfoSection: {
    marginBottom: 40,
    alignItems: "center",
  },
  duenioInfoCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 28,
    maxWidth: 400,
    width: "100%",
    borderWidth: 1,
    borderColor: colors.border.light,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 1,
  },
  duenioInfoSubtitle: {
    fontSize: 15,
    color: colors.text.secondary,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 20,
  },
  duenioBullets: {
    marginBottom: 24,
  },
  duenioBulletRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  duenioBulletIcon: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.brand.accentLanding,
    marginRight: 10,
  },
  duenioBulletText: {
    fontSize: 14,
    color: colors.text.primary,
    flex: 1,
  },
  duenioCta: {
    backgroundColor: colors.brand.accentLanding,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    alignItems: "center",
  },
  duenioCtaText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.text.inverse,
  },
  prestadorInfoSection: {
    marginBottom: 40,
    alignItems: "center",
  },
  prestadorInfoCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 28,
    maxWidth: 560,
    width: "100%",
    borderWidth: 1,
    borderColor: colors.border.light,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 1,
  },
  categorySection: {
    marginBottom: 40,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    gap: 8,
  },
  categoryIcon: {
    fontSize: 20,
  },
  categoryTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text.primary,
  },
  prestadorSubtitle: {
    fontSize: 15,
    color: colors.text.secondary,
    textAlign: "center",
    marginBottom: 24,
  },
  cardsRow: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 16,
  },
  planCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    minWidth: 220,
    maxWidth: 260,
    borderWidth: 1,
    borderColor: colors.border.light,
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 1,
  },
  planCardRecommended: {
    borderColor: colors.brand.accentLanding,
    borderWidth: 1.5,
    shadowColor: colors.brand.accentLanding,
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    transform: [{ scale: 1.0 }],
  },
  planCardRecommendedPrestador: {
    borderColor: colors.brand.lightBlue,
    borderWidth: 1.5,
    shadowColor: colors.brand.lightBlue,
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    transform: [{ scale: 1.0 }],
  },
  recommendedBadge: {
    position: "absolute",
    top: -10,
    alignSelf: "center",
    backgroundColor: colors.brand.accentLanding,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    shadowColor: colors.brand.accentLanding,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  recommendedBadgePrestador: {
    position: "absolute",
    top: -10,
    alignSelf: "center",
    backgroundColor: colors.brand.lightBlue,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    shadowColor: colors.brand.lightBlue,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  recommendedText: {
    color: colors.text.inverse,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  planHeader: {
    alignItems: "center",
    marginBottom: 20,
  },
  planName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text.primary,
    marginBottom: 12,
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 3,
  },
  planPrice: {
    fontSize: 28,
    fontWeight: "700",
    color: colors.brand.accentLanding,
  },
  planPricePrestador: {
    color: colors.brand.lightBlue,
  },
  planPeriod: {
    fontSize: 13,
    color: colors.text.secondary,
    fontWeight: "400",
  },
  ctaButton: {
    marginTop: 16,
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: colors.brand.accentLanding,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: "center",
  },
  ctaButtonPrestador: {
    borderColor: colors.brand.lightBlue,
  },
  ctaButtonRecommended: {
    backgroundColor: colors.brand.accentLanding,
    borderColor: colors.brand.accentLanding,
  },
  ctaButtonRecommendedPrestador: {
    backgroundColor: colors.brand.lightBlue,
    borderColor: colors.brand.lightBlue,
  },
  ctaButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.brand.accentLanding,
  },
  ctaButtonTextPrestador: {
    color: colors.brand.lightBlue,
  },
  ctaButtonTextRecommended: {
    color: colors.text.inverse,
  },
});

export default styles;

